### ISSUE TITLE
HTML Class Suggestions Extension locks up whole of VS Code v1.3 or v1.3.1

### ISSUE THREAD

**Issue by Howshall** [andersea/HTMLClassSuggestionsVSCode#1]
Believe change in behaviour as of VS Code v1.3 means that this extension now fully locks up Visual Studio Code as of v1.3 or later release while running to index CSS classes within a page/project.

Previously I was using Zignd's original https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion extension with no problems under VSCode v1.1 or v1.2, but this stopped working and causes same lockup behaviour under VSCode v1.3, which is when I then tried your extension to see if your code had the same problem or not.

I have reported this issue to Microsoft on main VSCode Issues list, but currently they have closed this issue until/unless extension authors can identify a change in VSCode v1.3 that is causing this change and break in behaviour https://github.com/Microsoft/vscode/issues/9200 

For reference I have also reported this issue to Zignd's extension issues list https://github.com/Zignd/HTML-CSS-Class-Completion/issues/22

**Comment by andersea** [comment]
Hi. Thanks for trying out my extension.

I have tried to reproduce this, both in debug mode and when installed from marketplace, but I have not been able to.

Can you provide some more information on your system? What OS you are running?

Which visual studio code extensions are you using?

Also information on your project would be useful. What CSS packages are you using? How many CSS files are in your project? Can you provide a sample project.json that I can test with?

**Comment by Howshall** [comment]
Thank you very much for coming back to me Anders 👍 

My system is a Windows 8.1 64Bit OS running on a Lenovo Core i7 laptop with 16Gb RAM

Only currently using 3x VS code extensions:
1) Can I Use - https://marketplace.visualstudio.com/items?itemName=akamud.vscode-caniuse 
2) HTMLHint - https://marketplace.visualstudio.com/items?itemName=mkaufman.HTMLHint
3) Your HTML Class Suggestions - https://marketplace.visualstudio.com/items?itemName=AndersEAndersen.html-class-suggestions

The project that I get 100% reproducible VS Code lockup in v1.3+ is a static HTML templates projects containing about 160 HTML page templates but a reasonably simple linked CSS structure of only 3x files + 1x additional IE Conditional hacks style sheet (attached is '_empty-page.html' which does lockup VS Code when opened from within folder view)

[_empty-page.html.txt](https://github.com/andersea/HTMLClassSuggestionsVSCode/files/371916/_empty-page.html.txt)

In doing further testing I can confirm VS Code lockup still present when I uninstall all except your CSS Class Suggestions extension, and doesn't occur if your CSS extension isn't installed (with or without the other 2x extensions)

One interesting behaviour I did find though in trying to bundle up a set of files to help you reproduce this error your end is that if I copied the entire project to a different drive with a shorter directory path than I couldn't replicate the VS Code lockup problem?

The location path I'm having problems with this project is C:\Users\700952470\Documents_Projects\BT MyDonate Fundraisers__SVN Repository\eFundHTMLTemplates

Whereas I haven't yet been able to replicate lockup issue when full project is copied to D:\Temp\eFundHTMLTemplates instead.

Could there be a file/path length limit that has changed as of VS Code v1.3? 
As Zignd's extension was working fine at this same path location with VS Code v1.0-1.2. Unfortunately I didn't have your extension installed under those earlier versions, so can only assume it would have run fine.

If you can point me to any VS Code or Extension error logs I'm happy to provide those. Appreciate difficult for you to work on any sort of fix until you can replicate!

**Comment by andersea** [comment]
I have done some additional testing.
- Pathnames longer than windows MAX_PATH (Ok)
- Exact path that you had problems with (Ok)
- Created over 160 html templates in workspace (Ok)

I did manage to get it to hang by doing something which is not a good idea to do, namely making many identical copies of the same bootstrap dist folder. This will cause a high load as the parser tries to remove identical class names from the collection of available class names. If you add too many, the system will simply hang.

I will try to make some adjustments to see if I can optimize this process. I dont think this is the cause of your issue, though.

You also mention logs. There are none by default that I am aware of, but it is possible I can add some.

**Comment by Howshall** [comment]
Thank you for all that additional testing. I think you have actually found the root cause of my problem (in terms of multiple same class declarations) as within the problem project folder I did have 3x copies of CKEditor Rich Text Editor resources folders (due to alternate prototyping I was doing)

Those each had about 20+ CSS files in their respective directories, but I didn't think that would be an issue as I assumed that the CSS extensions only looked at rules in the CSS files that were linked directly from the opened HTML page. Not try and index all possible CSS files within directory+sub folders!

So while the simplest _empty-page.html template I was opening (and still getting VS Code lockup) does only reference/use the 4x CSS files that I mentioned. But if your extension is indexing all possible CSS files within my HTML Prototypes folder/sub-folders it would have found 135x .css files to index and de-dup!

Investigating if the number of found CSS files was the root cause of VS Code lockup problem I temporarily deleted 2 out of 3 of the CKEditor http://ckeditor.com/ resource folders I had within the project, taking the number of .css files from 135x to 79x and did stop VS Code locking up on me so far in repeat testing of same simplest _empty-page.html file opening :-) 

At the moment looks like I can still avoid VS Code lockup issue if I just delete 1 out of 3 CKEditor resource folders (which is okay for what I need to actively keep/work on atm) 
I'll let you know if I get any further issues with currently reduced .css files numbers + if issue still exists if I remove the other remaining CKEditor resources folder.

Is the parser part of your extension or VS Code? Odd that this problem didn't seem to occur under VS Code 1.2 or less, as that project folder did have the same number of .css files previously.
While it did take a while for CSS parsing to complete I didn't know to expect any different, and VS Code never locked up pre-v1.3 while CSS parsing (At least with Zignd's extension)

Would be very interested in helping you test any further optimised extension as sounds like I may actually have a worst case scenario project after all!

**Comment by andersea** [comment]
This matches my findings.

Surprisingly, after doing some rudimentary profiling of my code, it seems the issue is not actually with the deduplication of css classes. That is done using the build in [javascript set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set), and it seems to be very fast, even for a large number of strings.

Instead, the evidence is pointing towards the `openTextDocument` vscode api call, which is used to open and read the css files. It looks like this function performs badly when you try to open a large number of files. This may be by design, though, since files opened using `openTextDocument`, are meant to be editable later in the editor, and therefore consume some extra ressources to support that. 

There are some options for working around that, the most obvious being replacing the `openTextDocument` call with some other more basic filesystem call that uses less resources.

**Comment by andersea** [comment]
Could you try this version:

[html-class-suggestions-0.1.1.vsix.zip](https://github.com/andersea/HTMLClassSuggestionsVSCode/files/375492/html-class-suggestions-0.1.1.vsix.zip)

(Unpack and Install from a command line using `code html-class-suggestions-0.1.1.vsix`, you may need to uninstall marketplace version first.)

This does 250 css files in 15 seconds on my machine. The majority of time is spent parsing CSS. If this isn't fast enough, the next step, I think, would be to try to eliminate duplicate files before parsing.

**Comment by Howshall** [comment]
Hi Anders. got that new v0.1.1 extension installed and working. 

Looks like that does avoid VS Code lockup even if I restore the 3rd copy of CKEditor resources that I had to remove previously as workaround :-)

Unfortunately I'm on leave for 1.5 weeks after end of today, but initial testing today looks like this v0.1.1 version fixes things for me at the moment. Suggest and happy for you to close this bug as resolved and I can always come back and ask for a re-open if I hit problems in further testing during August? 

But at the moment my issue seems to be fixed for my problem project of 266 HTML + 82 CSS files across a significant number of sub directories and 3x CKEditor resource directories which contain a significant amount of duplicate CSS rules.

Many thanks for all your diagnostics and rapid patching! Alan
