### ISSUE TITLE
Create an Atom equivalent

### ISSUE THREAD

**Issue by florianbouvot** [andersea/HTMLClassSuggestionsVSCode#15]
@andersea Hi, I was wondering if you can create a similar plugin for Atom ?

**Comment by andersea** [comment]
Thanks for your suggestion. I have no interest in Atom though. I haven't tried it in a long time, but when I did try it, I hated the experience thoroughly, so I don't think I will ever consider it again. VSC is pretty much what I need, so that is what I will support.

**Comment by florianbouvot** [comment]
@andersea I understand, thank you.
