### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by iksunnysingh** [andersea/HTMLClassSuggestionsVSCode#20]
- Issue Type: `Performance`
- Extension Name: `html-class-suggestions`
- Extension Version: `1.0.7`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.42.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Sunny Singh\AndersEAndersen.html-class-suggestions-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by andersea** [comment]
This version of Windows is not supported.
