### ISSUE TITLE
extension makes file save slow

### ISSUE THREAD

**Issue by holkmann** [andersea/HTMLClassSuggestionsVSCode#24]
Hi,

i use your extension under Windows 10 Pro x64. As a result, the process to save a file takes 2-3 seconds instead than instant. When i disable your extension, everything goes fine. Hope these informations are helping, because it's a great extension and i'd like to use it again when fixed. Thanks for your work!

VS Code Infos:
```
Version: 1.46.1 (user setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```
![installed-extensions](https://user-images.githubusercontent.com/11685841/85883985-2cc7b980-b7e2-11ea-9089-1e630e8c19dc.png)

**Comment by andersea** [comment]
How many CSS files is in your project folder, including all subfolders?

**Comment by holkmann** [comment]
> How many CSS files is in your project folder, including all subfolders?

Seven (7).

**Comment by andersea** [comment]
Closing this. The plugin obviously works for most people.
