### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by trihai306** [andersea/HTMLClassSuggestionsVSCode#26]
- Issue Type: `Bug`
- Extension Name: `html-class-suggestions`
- Extension Version: `1.1.1`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.56.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by andersea** [comment]
Closed due to lack of info.
