### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by muhzulzidan** [andersea/HTMLClassSuggestionsVSCode#27]
- Issue Type: `Bug`
- Extension Name: `html-class-suggestions`
- Extension Version: `1.1.1`
- OS Version: `Linux x64 5.8.0-53-generic`
- VS Code version: `1.56.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by andersea** [comment]
Not enough info.
