### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by oldSarge98** [andersea/HTMLClassSuggestionsVSCode#28]
- Issue Type: `Bug`
- Extension Name: `html-class-suggestions`
- Extension Version: `1.1.1`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.58.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by oldSarge98** [comment]
I have no idea what or how I created this. Apologies for wasting resources.

**Comment by andersea** [comment]
@lupulinist No worries m8. Nice to hear back. Happens a lot for some reason. Probably some instrumentation thing in vscode.
