### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by ChristianProgramacion** [andersea/HTMLClassSuggestionsVSCode#32]
- Issue Type: `Bug`
- Extension Name: `html-class-suggestions`
- Extension Version: `1.1.1`
- OS Version: `Windows_NT x64 6.3.9600`
- VS Code version: `1.69.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by andersea** [comment]
Not enough info.
