### ISSUE TITLE
[Feature Request] Add React (JSX) support

### ISSUE THREAD

**Issue by matronator** [andersea/HTMLClassSuggestionsVSCode#33]
Currently, there is no autocomplete in JSX `className` props for CSS classes. Please add a support for React and JSX/TSX as well.

**Comment by matronator** [comment]
Thanks @ultrox ! :)

**Comment by andersea** [comment]
This feature was kindly contributed by [Marko Vujanic](https://github.com/ultrox)! Thanks to him for this great work. Would probably never have been implemented without a contribution.
