### ISSUE TITLE
add new class not show in html class attribute

### ISSUE THREAD

**Issue by jing2si** [andersea/HTMLClassSuggestionsVSCode#4]
when i add new class in css file. 
it not show in html class attribute until reopen vscode.

> windows 10
> vscode 1.4.0
> HTML Class Suggestions 0.2.0

**Comment by andersea** [comment]
Yes, this is an issue. Currently css is only scanned when you first open an html file. If you edit the css, the changes are not taken into account.

**Comment by andersea** [comment]
Fixed in release 0.2.1.

**Comment by florianbouvot** [comment]
@andersea I've the same issue with current VSCode version (I've try to disable all others extensions).

I work with Sass to CSS using Gulp.

**Comment by andersea** [comment]
The extension is not able to see that css files change because of a build action, so it doesn't refresh the available classes. This scenario is simply not supported currently. 

I consider it a separate issue from this issue. Feel free to open a feature request.
