### ISSUE TITLE
Support php files

### ISSUE THREAD

**Issue by Sarkanyolo** [andersea/HTMLClassSuggestionsVSCode#5]
This plugin is great, but it only triggers on html files.
Please, make it work with php files also!

**Comment by andersea** [comment]
Could you elaborate a bit on what you would like to see? Last I worked with php, i recall it working best in conjunction with some kind of templating system. Are you asking for support for a specific template syntax?

**Comment by Sarkanyolo** [comment]
Thank you for the quick response!

I can make your plugin work with php file types by modifying these two lines:

**extension.js:**
- var disposable = vscode_1.languages.registerCompletionItemProvider('_html_', provider);
- var disposable = vscode_1.languages.registerCompletionItemProvider('_php_', provider);

**package.json:**
- "onLanguage:_html_"
- "onLanguage:_php_"

If you could somehow add both, it would work for .html and .php files also.
Lots of PHP frameworks need you to include html into .php files, like Laravel (app.blade.php).

Thank you for your help

**Comment by andersea** [comment]
I guess we can do that, but I feel like there would be some edge cases where it may not work. I guess we can deal with that later.

**Comment by andersea** [comment]
Could you try this version?

[html-class-suggestions-0.2.1.vsix.zip](https://github.com/andersea/HTMLClassSuggestionsVSCode/files/464461/html-class-suggestions-0.2.1.vsix.zip)

**Comment by Sarkanyolo** [comment]
Works like charm, thank you for your efforts!

**Comment by Sarkanyolo** [comment]
Can you please release this version?

**Comment by andersea** [comment]
This feature is in v1.0.0. Thanks for your suggestion.
