### ISSUE TITLE
bootstrap in node_modules folder

### ISSUE THREAD

**Issue by markiianharbych** [andersea/HTMLClassSuggestionsVSCode#8]
Hi!

I have an angular 2 project, using angular cli library. I've installed bootstrap as a nodejs module. Angular cli using it's config file and then webpack - attaches bootstrap files to my web site.

And the issue is that I cannot see any suggestions in Visual Studio Code.

Any help on this?

**Comment by andersea** [comment]
Can you make an example project that reproduces this?

**Comment by andersea** [comment]
Closing due to no communication.
